version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  db:
    driver: local
